remote_theme: daattali/beautiful-jekyll@5.0.0

# Site settings
title: Belal Ahmed Siddiqui - Portfolio
description: Welcome To My Portfolio

# Social media links
social-network-links:
  email: "belalahmedsiddiqui8@gmail.com"
  github: stoicsapien1
  linkedin: stoicsapien1
  quora: BELAL-AHMED-SIDDIQUI-2

# Navbar links
navbar-links:
  GitHub: "https://github.com/stoicsapien1"
  LinkedIn: "https://www.linkedin.com/in/stoicsapien1"
  Quora: "https://www.quora.com/profile/BELAL-AHMED-SIDDIQUI-2"
