remote_theme: daattali/beautiful-jekyll@5.0.0
title: Belal Ahmed Siddiqui - Portfolio
description: Welcome To My Portfolio.
navbar-links:
  About Me: "aboutme"
  Projects: "projects"
  Contact: "contact"
social-network-links:
  email: "your-email@example.com"
  github: your-github-username
  linkedin: your-linkedin-username
