remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Your Name - Portfolio
description: Welcome to my professional portfolio
readme_index:
  enabled: true
  remove_originals: false
github:
  is_project_page: false

