remote_theme: daattali/beautiful-jekyll@5.0.0
title: Belal Ahmed Siddiqui - Portfolio
description: Welcome To My Portfolio.

social-network-links:
  email: "belalahmedsiddiqui8@gmail.com"
  github: stoicsapien1
  linkedin: stoicsapien1
