title: Belal Ahmed Siddiqui
logo: assets/img/profile.jpg
description: Welcome To My Portfolio.
show_downloads: false

# Set the theme
theme: minimal-mistakes-jekyll

# Additional configuration options for Minimal Mistakes
minimal_mistakes_skin: "air"
